### ISSUE TITLE
Add "Development" Section to README

### ISSUE THREAD

**Issue by jhnsnc** [tweenrex/tweenrex#4]
Consider adding a brief section to the README in each repo about how to build/test the project locally.

- install TS
- configure env for TS linting etc
- writing/running tests
- add `watch`/`dev` script to `package.json`(?) (to watch src files)

**Comment by notoriousb1t** [comment]
I think that is a good idea.  I'll walk through and add some notes.  I don't think we have tslint as part of the pipeline.  I have only been using it through a vscode plugin.

**Comment by notoriousb1t** [comment]
How is this? https://github.com/tweenrex/empty-project

I added build:watch, test:watch, and npm start to run them concurrently.  I also added a longer contributor section.

**Comment by jhnsnc** [comment]
👍 I updated my files to incorporate these changes.

**Comment by notoriousb1t** [comment]
Okay, I will update @tweenrex/render and then mark this as closed afterward

**Comment by notoriousb1t** [comment]
Alright, all repos have been updated
