### ISSUE TITLE
clamping 2 values, regarding interpolation from 0 to 1

### ISSUE THREAD

**Issue by flowen** [tweenrex/tweenrex#8]
as discussed on slack, I would love to see a feature in which we can define a start and end (in px or relative units such as vw/vh, %, etc) point for the X and/or Y axis. To create fixed animations between this fixed points.

example:
Scrolling from left to right, animation A is triggered on 75vw and the animation ends on 50vw. So basically the animation length interpolates between 0 and 1 relative to these offsets (75vw = 0, 62.5vw = 0.5, 50vw = 1)

**Comment by notoriousb1t** [comment]
I think percentage based is covered by the offset value, but there is no way to clamp based on pixels in the lib as it stands now.  Here is what I propose:

```js
var scroller = TyrannoScrollus({
      targets: '.container',
      direction: 'y', 
      clampFrom: 0, // 0px
      clampTo: 200 // 200px
})

scroller.play()
```

I'm not 100% on the names there, but 

- if clampFrom is not specified, 0 offset is defaulted.
- if clampTo is not specified, 1 offset is defaulted.

I'm not opposed to supporting relative units, but I think out of the gate, we should start with supporting pixels.  Once we have a utility function for converting relative units to pixels, we can round-robin back and add relative functionality.

Thoughts @shshaw  and @jhnsnc ?

**Comment by shshaw** [comment]
Would `start` and `end` or a variant of those be more appropriate? Seems like the animation would start at the first value, then end at the last value.

**Comment by notoriousb1t** [comment]
I have no issue with start/end.  But it essentially would be 0 until start and be 1 after end in that case.

**Comment by shshaw** [comment]
Right. `startAt`/`endAt` might be clearer.

**Comment by notoriousb1t** [comment]
@flowen, this has been published in @tweenrex/core 1.2.9 as startAt/endAt in the constructor of TyrannoScrollus.  Please give it a try and let us know.

**Comment by flowen** [comment]
works perfect! thank you so much

**Comment by flowen** [comment]
works perfect! thank you so much
